### ISSUE TITLE
`clojure-csv.core` in Homework 2

### ISSUE THREAD

**Issue by kcy1019** [hongseok-yang/probprog18#1]
I don't know whether everyone has same issue, but in my case, I encountered an error saying Clojure could not locate the package.

This error can be resolved by modifying project.clj:
1. Add `[clojure-csv/clojure-csv "2.0.1"]` line to `:dependencies [...]`
2. Run `$ lein deps` to install missing dependencies.
3. Re-launch Gorilla REPL to apply updated dependencies.

**Comment by hongseok-yang** [comment]
Thank you very much! I will share this information in KLMS and the course webpage.

Best wishes,
Hongseok
